20230117_add_api_endpoints_santa_rules
zentralopensource/zentral pull request #607
Opened 2023-01-20 15:24 UTC by xarbit

2023-01-23 06:21 UTC, np5 requested changes

2023-01-23 06:21 UTC, np5 commented on zentral/contrib/santa/serializers.py
> +        return rule
If you want to add the events in this PR, you should also post an event here. see https://github.com/zentralopensource/zentral/blob/d301166954f7b754d90252791afb2bdca1ef4bcf/zentral/contrib/santa/views/setup.py#L294-L295

2023-01-23 06:21 UTC, np5 commented on tests/santa/test_api_views.py
> +    def test_update_rule_change_target_identifier_error(self):
It should be possible to change a rule target

2023-01-23 06:21 UTC, np5 commented on tests/santa/test_api_views.py
> +    def test_update_rule_change_target_type_error(self):
It should be possible to change a rule target

2023-01-23 06:21 UTC, np5 commented on tests/santa/test_api_views.py
> +
You should add tests to trigger all the conditions in the building of the update rule event.

2023-01-23 07:09 UTC, xarbit commented on zentral/contrib/santa/serializers.py
> +class RuleMixin:
Thx. Yes, wanted to change that today, that is why I marked it as "Draft"

2023-01-24 12:37 UTC, np5 requested changes

2023-01-24 12:37 UTC, np5 commented on zentral/contrib/santa/serializers.py
> +            instance.version = F("version") + 1
You should bump the version if any one of the attribute is changed.

2023-01-25 14:12 UTC, np5 approved these changes

2023-01-25 14:12 UTC, merged